include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_final_fields
    - avoid_print
    - prefer_single_quotes
    - require_trailing_commas


