import 'package:orbithub/mcp/tool_registry.dart';
import 'package:orbithub/mcp/json/json_converter.dart';
import 'package:orbithub/mcp/generated/mcp_tool_executor.g.dart' as generated;
import 'package:logging/logging.dart';

/// Executor for MCP tools.
/// 
/// Provides type-safe execution of MCP tools.
/// Execution logic is auto-generated by build_runner.
class McpToolExecutor {
  static final Logger _logger = Logger('McpToolExecutor');

  /// Execute a tool by name with arguments.
  /// 
  /// [toolName] The name of the tool to execute
  /// [arguments] Map of parameter names to values
  /// [clientInstances] Map of client instances (jira, confluence, etc.)
  /// 
  /// Returns the result of tool execution
  static Future<dynamic> executeTool(
    String toolName,
    Map<String, dynamic> arguments,
    Map<String, dynamic> clientInstances,
  ) async {
    final tool = McpToolRegistry.getTool(toolName);
    if (tool == null) {
      throw ArgumentError('Unknown tool: $toolName');
    }

    _logger.info('Executing tool: $toolName');

    // Use generated executor code
    return await generated.executeTool(toolName, arguments, clientInstances);
  }

  /// Convert parameter value to appropriate type.
  static dynamic convertParameter(
    dynamic value,
    String targetType,
    String paramName,
  ) {
    return JsonConverter.fromJsonValue(value, targetType);
  }
}

